import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import QueryProvider from "@/components/providers/QueryProvider"
import ThemeProvider from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/sonner"
import { AuthProvider } from "@/context/authContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}

      >
        <AuthProvider>
          <ThemeProvider>
            <QueryProvider>
              <Navbar />
              {children}
              <Toaster position="top-center" richColors />
              <Footer />
            </QueryProvider>
          </ThemeProvider>
        </AuthProvider>

      </body>
    </html>
  );
}
